FROM oven/bun:1

WORKDIR /app

COPY package*.json bun.lock ./


RUN bun install --frozen-lockfile

COPY . .
EXPOSE 5000

CMD ["sh", "-c", "bunx drizzle-kit push && bun run src/db/seed.ts && bun src/index.ts"]